runtime: nodejs18
service: default

# Force HTTPS
handlers:
  - url: /static
    static_dir: build/static
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      Referrer-Policy: "strict-origin-when-cross-origin"
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://tugas6-backend-749281711221.us-central1.run.app; font-src 'self' data:;"

  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json
    secure: always
    http_headers:
      Content-Type: "application/manifest+json"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"

  - url: /robots.txt
    static_files: build/robots.txt
    upload: build/robots.txt
    secure: always

  - url: /(.*\.(js|css|ico|png|jpg|svg|woff|woff2))$
    static_files: build/\1
    upload: build/.*\.(js|css|ico|png|jpg|svg|woff|woff2)$
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"
      X-Content-Type-Options: "nosniff"

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      Referrer-Policy: "strict-origin-when-cross-origin"
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://tugas6-backend-749281711221.us-central1.run.app; font-src 'self' data:;"
      Cache-Control: "no-cache, no-store, must-revalidate"

env_variables:
  NODE_ENV: production
